/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyAGN;

/**
 *
 * @author Shahryar
 */
public class agnGUI extends javax.swing.JFrame {
    
    private AGN agn;

    /**
     * Creates new form MainFrame
     */
    public agnGUI() {
        initComponents();
        agn = new AGN();
        setTitle("Main AGN");
    }
    
    /**
     * getter for for AGN object 
     * @return AGN object
     */
    public AGN getAGN()
    {
        return agn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        recordChildBtn = new javax.swing.JButton();
        recordContributionBtn = new javax.swing.JButton();
        viewContributionBtn = new javax.swing.JButton();
        viewSponsorshipBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        recordChildBtn.setText("Record Child");
        recordChildBtn.setMaximumSize(new java.awt.Dimension(129, 23));
        recordChildBtn.setMinimumSize(new java.awt.Dimension(129, 23));
        recordChildBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        recordChildBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordChildBtnActionPerformed(evt);
            }
        });

        recordContributionBtn.setText("Record Contribution");
        recordContributionBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        recordContributionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordContributionBtnActionPerformed(evt);
            }
        });

        viewContributionBtn.setText("View Contribution");
        viewContributionBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        viewContributionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewContributionBtnActionPerformed(evt);
            }
        });

        viewSponsorshipBtn.setText("View Sponsorship");
        viewSponsorshipBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        viewSponsorshipBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSponsorshipBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Acts Global Networking");
        jLabel1.setToolTipText("");
        jLabel1.setMaximumSize(new java.awt.Dimension(309, 26));
        jLabel1.setMinimumSize(new java.awt.Dimension(309, 26));
        jLabel1.setPreferredSize(new java.awt.Dimension(309, 26));

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("AGN Adminstrator");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(recordContributionBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(recordChildBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(viewContributionBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(viewSponsorshipBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(recordChildBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(recordContributionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(viewContributionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewSponsorshipBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * action when recordChildBtn button is clicked
     * creates and opens RecordChildDialog object 
     * @param evt 
     */
    private void recordChildBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordChildBtnActionPerformed
        // TODO add your handling code here:
        RecordChildDialog rcGUI = new RecordChildDialog(this, true);
        rcGUI.setVisible(true);
    }//GEN-LAST:event_recordChildBtnActionPerformed

    /**
     * action when viewContributionBtn button is clicked
     * creates and opens ViewContributionWindow object 
     * @param evt 
     */
    private void viewContributionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewContributionBtnActionPerformed
        // TODO add your handling code here:
        ViewContributionWindow vcw = new ViewContributionWindow(agn, this);
        vcw.setLocationRelativeTo(this);
        vcw.setVisible(true);
    }//GEN-LAST:event_viewContributionBtnActionPerformed

    /**
     * action when viewSponsorshipBtn button is clicked
     * creates and opens ViewSponsorshipWindow object 
     * @param evt 
     */
    private void viewSponsorshipBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSponsorshipBtnActionPerformed
        // TODO add your handling code here:
        ViewSponsorshipWindow vsw = new ViewSponsorshipWindow(agn, this);
        vsw.setVisible(true);
    }//GEN-LAST:event_viewSponsorshipBtnActionPerformed

    /**
     * action when recordContributionBtn button is clicked
     * creates and opens RecordContributionDialog object 
     * @param evt 
     */
    private void recordContributionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordContributionBtnActionPerformed
        // TODO add your handling code here:
        RecordContributionDialog rcfGUI = new RecordContributionDialog(this, true);
        rcfGUI.setLocationRelativeTo(this);
        rcfGUI.setVisible(true);
    }//GEN-LAST:event_recordContributionBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agnGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agnGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agnGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agnGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agnGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton recordChildBtn;
    private javax.swing.JButton recordContributionBtn;
    private javax.swing.JButton viewContributionBtn;
    private javax.swing.JButton viewSponsorshipBtn;
    // End of variables declaration//GEN-END:variables
}
