package MyAGN;

import java.time.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Shahryar
 */
public class MaterialDialog extends javax.swing.JDialog {
    
    /**
     * Internal attributes of a Material dialog
     */
    private AGN agn;
    private Donor theDonor;
    private Material mat;
    private MaterialType mt;
    

    /**
     * Constructor for MaterialDialog
     * @param parent
     * @param modal
     * @param theDonor 
     */
    public MaterialDialog(java.awt.Frame parent, boolean modal, Donor theDonor) {
        super(parent, modal);
        this.agn = ((agnGUI) parent).getAGN();
        this.theDonor = theDonor;
        initComponents();
        setTitle("Record Material Contribution");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGType = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        schoolBtn = new javax.swing.JRadioButton();
        foodBtn = new javax.swing.JRadioButton();
        clothingBtn = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        descriptionTF = new javax.swing.JTextField();
        valPerUnitTF = new javax.swing.JTextField();
        noContrTF = new javax.swing.JTextField();
        okBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Date");

        jLabel2.setText("Item Description");

        BGType.add(schoolBtn);
        schoolBtn.setText("School Supplies");

        BGType.add(foodBtn);
        foodBtn.setText("Food");

        BGType.add(clothingBtn);
        clothingBtn.setText("Clothing");

        jLabel3.setText("Value Per Unit");

        jLabel4.setText("Number of Units Contributed");

        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(noContrTF, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(117, 117, 117)
                                .addComponent(valPerUnitTF, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(schoolBtn)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(descriptionTF)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(foodBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(clothingBtn))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(okBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelBtn)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(descriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schoolBtn)
                    .addComponent(foodBtn)
                    .addComponent(clothingBtn))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(valPerUnitTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(noContrTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * action when ok button is clicked
     * @param evt 
     */
    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        // TODO add your handling code here:
        try
        {//validation
            boolean valid = false;
            if(date.getDate() == null)
                JOptionPane.showMessageDialog(this, "Enter the date!");
            else if(descriptionTF.getText().equals(""))
                JOptionPane.showMessageDialog(this, "Enter description!!");
            else if(BGType.getSelection() == null)
                JOptionPane.showMessageDialog(this, "Select type of Material");
            else if(valPerUnitTF.getText().equals(""))
                JOptionPane.showMessageDialog(this, "Enter value per unit");
            else if(noContrTF.getText().equals(""))
                JOptionPane.showMessageDialog(this, "Enter the number of units contributed");
            else
            {
                valid = true;
            }
            if(valid)
            {
                LocalDate theDate = date.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                
                String description = descriptionTF.getText();
                
                
                if (schoolBtn.isSelected()) 
                    mt = MaterialType.values()[0];
                else if (foodBtn.isSelected())
                    mt = MaterialType.values()[1];
                else if (clothingBtn.isSelected())
                    mt = MaterialType.values()[2];
                
                
                double value = Double.parseDouble(valPerUnitTF.getText());
                int contrNum = Integer.parseInt(noContrTF.getText());
                
                mat = theDonor.addMaterial(theDate, mt, description, value, contrNum);
                mat.setDonor(theDonor);
                this.dispose();
                
            }
        }
        catch(NumberFormatException nfe)
        {
            JOptionPane.showMessageDialog(this, "Both value per unit and number of units must be a number!");
        }
    }//GEN-LAST:event_okBtnActionPerformed

    /**
     * action when cancel button is clicked
     * @param evt 
     */
    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGType;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JRadioButton clothingBtn;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextField descriptionTF;
    private javax.swing.JRadioButton foodBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField noContrTF;
    private javax.swing.JButton okBtn;
    private javax.swing.JRadioButton schoolBtn;
    private javax.swing.JTextField valPerUnitTF;
    // End of variables declaration//GEN-END:variables
}
