package MyAGN;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.*;
/**
 *
 * @author Shahryar
 */
public class RecordContributionDialog extends javax.swing.JDialog {
    
    /**
     * Internal attributes of a record Contribution dialog
     */
    private AGN agn;
    private Donor theDonor;
    private agnGUI agnGui;

    /**
     * Constructor RecordContributionDialog
     * @param parent
     * @param modal 
     */
    public RecordContributionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        agn = ((agnGUI) parent).getAGN();
        initComponents();
        setTitle("Record Contribution");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGtype = new javax.swing.ButtonGroup();
        donorEmailLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        donorEmailTF = new javax.swing.JTextField();
        donorNameTF = new javax.swing.JTextField();
        sponsorshipBtn = new javax.swing.JRadioButton();
        materialBtn = new javax.swing.JRadioButton();
        monetaryBtn = new javax.swing.JRadioButton();
        OKBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        totContrLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        donorEmailLbl.setText("Donor's Email");

        jLabel2.setText("Donor's Name");

        jLabel3.setText("Total Contribution");

        donorNameTF.setEnabled(false);

        BGtype.add(sponsorshipBtn);
        sponsorshipBtn.setText("Sponsorship");
        sponsorshipBtn.setEnabled(false);

        BGtype.add(materialBtn);
        materialBtn.setText("Material");
        materialBtn.setEnabled(false);

        BGtype.add(monetaryBtn);
        monetaryBtn.setText("Monetary");
        monetaryBtn.setEnabled(false);

        OKBtn.setText("OK");
        OKBtn.setEnabled(false);
        OKBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(OKBtn)
                .addGap(28, 28, 28)
                .addComponent(cancelBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(donorEmailLbl)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(donorEmailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(searchBtn))
                                    .addComponent(donorNameTF))
                                .addGap(0, 2, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(totContrLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sponsorshipBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(materialBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monetaryBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(donorEmailLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(donorEmailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBtn))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(donorNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sponsorshipBtn)
                                    .addComponent(materialBtn)
                                    .addComponent(monetaryBtn)))
                            .addComponent(totContrLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(OKBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * action when search button is clicked with validation
     * @param evt 
     */
    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String donorEmail = donorEmailTF.getText();
        
        if(donorEmail.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter an email of the donor, please!");
        }
        
        if(!donorEmail.equals(""))
        {
            theDonor = agn.FindDonor(donorEmail);
        if(theDonor == null)
        {
            int opt = JOptionPane.showConfirmDialog(this, "Donor is not found. Create new donor?", "Not Found", JOptionPane.YES_NO_OPTION);
            if(opt == JOptionPane.YES_OPTION)
            {
                donorNameTF.setEnabled(true);
                materialBtn.setEnabled(true);
                monetaryBtn.setEnabled(true);
                sponsorshipBtn.setEnabled(true);
                donorEmailTF.setEnabled(false);
                searchBtn.setEnabled(false);
                OKBtn.setEnabled(true);
                
            }
            }
        else
            {
                donorNameTF.setText(theDonor.getDonorName());
                String total = Double.toString(theDonor.totalContributionValue());
                totContrLbl.setText(total);
                materialBtn.setEnabled(true);
                monetaryBtn.setEnabled(true);
                sponsorshipBtn.setEnabled(true);
                OKBtn.setEnabled(true);
                searchBtn.setEnabled(false);
                donorEmailTF.setEnabled(false);
            }
        }
        
        
    }//GEN-LAST:event_searchBtnActionPerformed

    /**
     * action when OK button is clicked with validation
     * @param evt 
     */
    private void OKBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKBtnActionPerformed
        // TODO add your handling code here:
        boolean valid = false;
        
        String donorEmail = donorEmailTF.getText();
        String donorName = donorNameTF.getText();
        
        if(donorEmail.equals(""))
            JOptionPane.showMessageDialog(this, "Email can not be blank!");
        else if(donorName.equals(""))
            JOptionPane.showMessageDialog(this, "Name can not be blank!");
        else if(BGtype.isSelected(null))
            JOptionPane.showMessageDialog(this, "Choose Contribution type!");
        else
            valid = true;
        
        if (valid) 
        {
            if(agn.FindDonor(donorEmail) == null)
                theDonor = agn.addDonor(donorName, donorEmail);

            if (monetaryBtn.isSelected()) 
            {
                agnGui = (agnGUI) this.getParent();
                MonetaryDialog md = new MonetaryDialog(agnGui, true, theDonor);
                md.setVisible(true);
                this.setVisible(false);
            } 
            else if (materialBtn.isSelected()) 
            {
                agnGui = (agnGUI) this.getParent();
                MaterialDialog matD = new MaterialDialog(agnGui, true, theDonor);
                matD.setVisible(true);
                this.setVisible(false);
            } 
            else if (sponsorshipBtn.isSelected()) 
            {
                NotFullySponChildWindow nfscw = new NotFullySponChildWindow(agn, theDonor);
                nfscw.setVisible(true);
                this.setVisible(false);
            }
            this.dispose();
        }
        
        
    }//GEN-LAST:event_OKBtnActionPerformed

    /**
     * action when cancel button is clicked
     * @param evt 
     */
    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecordContributionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecordContributionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecordContributionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecordContributionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RecordContributionDialog dialog = new RecordContributionDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGtype;
    private javax.swing.JButton OKBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel donorEmailLbl;
    private javax.swing.JTextField donorEmailTF;
    private javax.swing.JTextField donorNameTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton materialBtn;
    private javax.swing.JRadioButton monetaryBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JRadioButton sponsorshipBtn;
    private javax.swing.JLabel totContrLbl;
    // End of variables declaration//GEN-END:variables
}
