
package MyAGN;

import java.time.*;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Shahryar
 */
public class RecordChildDialog extends javax.swing.JDialog {
    
    /**
     * Internal attributes of a record child dialog
     */
    private AGN agn;
    private Child theChild;

    /**
     * Constructor for RecordChildDialog
     * @param parent
     * @param modal 
     */
    public RecordChildDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        agn = ((agnGUI) parent).getAGN();
        initComponents();
        setTitle("Record Child");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chidlNameLbl = new javax.swing.JLabel();
        MyKadLbl = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();
        dateOfBirthLbl = new javax.swing.JLabel();
        MyKadNoTF = new javax.swing.JTextField();
        ChildNameTF = new javax.swing.JTextField();
        ChildAddressTF = new javax.swing.JTextField();
        DateOfBirth = new com.toedter.calendar.JDateChooser();
        OKBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 340));

        chidlNameLbl.setText("Name");

        MyKadLbl.setText("MyKad Number");

        addressLbl.setText("Home Address");

        dateOfBirthLbl.setText("Date of Birth");

        ChildNameTF.setEnabled(false);

        ChildAddressTF.setEnabled(false);

        DateOfBirth.setEnabled(false);

        OKBtn.setText("OK");
        OKBtn.setEnabled(false);
        OKBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKBtnActionPerformed(evt);
            }
        });

        CancelBtn.setText("Cancel");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\rukhi\\OneDrive\\Рабочий стол\\javaUI4.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(OKBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(CancelBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChildNameTF)
                            .addComponent(ChildAddressTF)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chidlNameLbl)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(MyKadNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(DateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(dateOfBirthLbl)
                                    .addComponent(addressLbl)
                                    .addComponent(MyKadLbl))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MyKadLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MyKadNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chidlNameLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChildNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addressLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChildAddressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dateOfBirthLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CancelBtn)
                    .addComponent(OKBtn)))
        );

        MyKadNoTF.getAccessibleContext().setAccessibleName("");
        MyKadNoTF.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * action when Ok button is clicked with validation
     * @param evt 
     */
    private void OKBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKBtnActionPerformed
        // TODO add your handling code here:
       
        try 
        {
            boolean valid = false;
            
            String MyKadNumber = MyKadNoTF.getText();
            String name = ChildNameTF.getText();
            String address = ChildAddressTF.getText();
            LocalDate dateOfBirth = DateOfBirth.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            
            int age = LocalDate.now().getYear() - dateOfBirth.getYear();
       
            if (name.equals(""))
                JOptionPane.showMessageDialog(this, "Name can not be blank!");
            else if (address.equals(""))
                JOptionPane.showMessageDialog(this, "Home Address can not be blank!");
            else if (dateOfBirth.isAfter(LocalDate.now()))
                JOptionPane.showMessageDialog(this, "You can not record a child that was not born yet!");
            else if (age > 18)
                JOptionPane.showMessageDialog(this, "Age can not be above 18!");
            else
                valid = true;
            
            if(valid)
            {
                if(agn.findChild(MyKadNumber) != null)
                {
                    agn.findChild(MyKadNumber).setChildName(name);
                    agn.findChild(MyKadNumber).setDateOfBirth(dateOfBirth);
                    agn.findChild(MyKadNumber).setHomeAddress(address);
                    JOptionPane.showMessageDialog(this, name+" with MyKad number:"+MyKadNumber+" updated successfully");
                }
                else
                {
                    agn.addChild(name, MyKadNumber, address, dateOfBirth);
                    JOptionPane.showMessageDialog(this, name+" with MyKad number:"+MyKadNumber+" added successfully");
                }
                
                this.dispose();    
            }
        } 
        catch (NullPointerException npe) 
        {
            JOptionPane.showMessageDialog(this, "Please, set the date of birth!");
        }
        
    }//GEN-LAST:event_OKBtnActionPerformed

    /**
     * action when cancel button is clicked
     * @param evt 
     */
    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelBtnActionPerformed

    /**
     * action when search button is clicked
     * @param evt 
     */
    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        
        String MyKadNumber = MyKadNoTF.getText();
        if(MyKadNumber.equals(""))
        {
            JOptionPane.showMessageDialog(this, "MyKad Number can not be empty!");
        }
        
        if(!MyKadNumber.equals(""))
        {
            if(agn.findChild(MyKadNumber) == null)
            {
                JOptionPane.showMessageDialog(this, "Child is not found. Please record the child!");
                ChildNameTF.setEnabled(true);
                ChildAddressTF.setEnabled(true);
                DateOfBirth.setEnabled(true);
                OKBtn.setEnabled(true);
                searchBtn.setEnabled(false);
                MyKadNoTF.setEnabled(false);
            }else{
                ChildNameTF.setText(agn.findChild(MyKadNumber).getChildName());
                ChildAddressTF.setText(agn.findChild(MyKadNumber).getHomeAddress());
                Date date = Date.from(agn.findChild(MyKadNumber).getDateOfBirth().atStartOfDay(ZoneId.systemDefault()).toInstant());
                DateOfBirth.setDate(date);
                ChildNameTF.setEnabled(true);
                ChildAddressTF.setEnabled(true);
                DateOfBirth.setEnabled(true);
                OKBtn.setEnabled(true);
                searchBtn.setEnabled(false);
                MyKadNoTF.setEnabled(false);
        }
        }
        
    }//GEN-LAST:event_searchBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JTextField ChildAddressTF;
    private javax.swing.JTextField ChildNameTF;
    private com.toedter.calendar.JDateChooser DateOfBirth;
    private javax.swing.JLabel MyKadLbl;
    private javax.swing.JTextField MyKadNoTF;
    private javax.swing.JButton OKBtn;
    private javax.swing.JLabel addressLbl;
    private javax.swing.JLabel chidlNameLbl;
    private javax.swing.JLabel dateOfBirthLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton searchBtn;
    // End of variables declaration//GEN-END:variables
    
}
