package MyAGN;

import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import javax.swing.WindowConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Shahryar
 */
public class ViewSponsorshipWindow extends javax.swing.JFrame {
    
    /**
     * Internal attributes of a view sponsorship frame
     */
    private AGN theAGN;
    private ViewSponsorshipTableModel vstm;
    private agnGUI theParent;
    private SponsorTableModel stm;

    /**
     * constructor that Creates new form ViewSponsorshipWindow
     * @param theAGN
     * @param parentWindow 
     */
    public ViewSponsorshipWindow(AGN theAGN, agnGUI parentWindow) {
        initComponents();
        this.theAGN = theAGN;
        theParent = parentWindow;
        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        theParent.setEnabled(false);
        setupModels();
        setTitle("View Sponsorship For Child");
    }
    
    /**
     * setting up model for ViewSponsorshipWindow
     */
    public void setupModels()
    {
        vstm = new ViewSponsorshipTableModel(theAGN.getAllChild());
        childTable.setModel(vstm);
        childTable.setAutoCreateRowSorter(true);

        childTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        childTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) 
            {
                updateTable();
            }
        });
        
    }
    
    /**
     * updating the second table when child is selected
     */
    public void updateTable()
    {  
        int row = childTable.getSelectedRow();	
        Child theChild = vstm.getChildAt(row);
        
        
        stm = new SponsorTableModel(theAGN.getAllSponsor());
        sponsorTable.setModel(stm);
        sponsorTable.setAutoCreateRowSorter(true);
        stm.setSpon(theChild.findSponsor());
        sponsorTable.removeAll();
        stm.fireTableDataChanged();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        childTable = new javax.swing.JTable();
        closeBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        sponsorTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        childTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(childTable);

        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        sponsorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(sponsorTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(closeBtn))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * action when close button is clicked 
     * @param evt 
     */
    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // TODO add your handling code here:
        
        theParent.setEnabled(true);
        this.setVisible(false);
    }//GEN-LAST:event_closeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable childTable;
    private javax.swing.JButton closeBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable sponsorTable;
    // End of variables declaration//GEN-END:variables
}
